imports:
    - { resource: parameters.yml }
    - { resource: assets_version.php }

framework:
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version_format: rev-%%2$s/%%1$s
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    node: "%node_path%"
    filters:
        cssrewrite: ~
        compass:
            bin: '%assetic_compass%'
            style: 'expanded'
            images_dir: '%kernel.root_dir%/../web/bundles'
            http_images_path: '/bundles'
            apply_to: "\.scss$"
        uglifyjs2:
            bin: '%uglifyjs%'
            compress: true
            mangle: true
